Fix --entrypoint issue, add --rm
Currently stuck on this:

ERROR: unable to server-add 165.225.189.56:8091 (400) Bad Request
[u'Failed to reach erlang port mapper. Timeout connecting to "165.225.189.56" on port "4369".  This could be due to an incorrect host/port combination or a firewall in place between the servers.']

Fix: use internal ip's instead of public ip's (I think)